services:
  nestjs:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
    env_file:
      - './.env'
    depends_on:
      - 'postgres'

  postgres:
    image: postgres:latest
    ports:
      - '5432:5432'
    env_file:
      - './.env'
    volumes:
      - postgres_data:/postgres/data

volumes:
  postgres_data:
